[versions]
androidGradlePlugin = "8.6.0"
kotlin = "1.9.22"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
activity = { group = "androidx.activity", name = "activity", version = "1.8.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }

junit = { group = "junit", name = "junit", version = "4.13.2" }
ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }
